<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shlook" failures="2" tests="4" name="Test" time="0.078" errors="0" timestamp="2023-05-26T01:48:43 EDT">
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestFour" time="0.011"/>
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestOne" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestOne(FailedTestCases.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestThree" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestThree(FailedTestCases.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestThree -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestTwo" time="0.003"/>
</testsuite> <!-- Test -->
